# 00. PyTorch Fundamentals Exercises

### 1. Documentation reading

A big part of deep learning (and learning to code in general) is getting familiar with the documentation of a certain framework you're using. We'll be using the PyTorch documentation a lot throughout the rest of this course. So I'd recommend spending 10-minutes reading the following (it's okay if you don't get some things for now, the focus is not yet full understanding, it's awareness):
  * The documentation on [`torch.Tensor`](https://pytorch.org/docs/stable/tensors.html#torch-tensor).
  * The documentation on [`torch.cuda`](https://pytorch.org/docs/master/notes/cuda.html#cuda-semantics).



In [ ]:
import torch
import numpy as np
import pandas as pd
import matplotlib.pyplot as plt
print(torch.__version__)

2.1.0+cu121


In [ ]:
# torch.tensor: multi-dimensional matrix containing elements of a single data type
#create a scalar
scalar = torch.tensor(7)

In [ ]:
scalar

tensor(7)

In [ ]:
scalar.ndim

0

In [ ]:
#vector= magnitud and direction
vector = torch.tensor([7,7])

In [ ]:
vector.ndim

1

In [ ]:
vector.shape

torch.Size([2])

In [ ]:
vector2 = torch.tensor([7,7,7])

In [ ]:
vector2.ndim

1

In [ ]:
vector2.shape

torch.Size([3])

In [ ]:
# Matrix
matrix = torch.tensor([[7,8], [2,3]])
matrix.ndim

2

In [ ]:





matrix.shape

torch.Size([2, 2])

In [ ]:
matrix[0]

tensor([7, 8])

In [ ]:
# Tensor
tensor = torch.tensor([[[1,2,3],[3,5,6],[4,2,8]]])
tensor.ndim

3

In [ ]:
tensor.shape

torch.Size([1, 3, 3])

In [ ]:
tensor[0]

tensor([[1, 2, 3],
        [3, 5, 6],
        [4, 2, 8]])

In [ ]:
tensor[0][0]

tensor([1, 2, 3])

In [ ]:
# random_tensor
# random tensor of size 3,4
r_tensor = torch.rand(3,4)
r_tensor


tensor([[0.1602, 0.4937, 0.3883, 0.1789],
        [0.6585, 0.5557, 0.5627, 0.0868],
        [0.4143, 0.7361, 0.2755, 0.1898]])

In [ ]:
r_tensor.ndim

2

In [ ]:
r_tensor.shape

torch.Size([3, 4])

In [ ]:
r_tensor1 = torch.rand(2,2,3)
r_tensor1

tensor([[[0.2608, 0.8885, 0.3887],
         [0.5187, 0.5463, 0.9829]],

        [[0.0778, 0.2758, 0.2582],
         [0.7953, 0.4359, 0.8100]]])

In [ ]:
r_tensor1.ndim

3

In [ ]:
random_image_rgb = torch.rand(3, 240, 240)
random_image_rgb.ndim

3

In [ ]:
random_image_rgb.shape

torch.Size([3, 240, 240])

In [ ]:
random_image_rgb

tensor([[[0.6617, 0.4009, 0.5843,  ..., 0.7197, 0.3061, 0.9838],
         [0.5130, 0.9750, 0.7063,  ..., 0.1177, 0.7781, 0.9942],
         [0.6471, 0.9696, 0.0586,  ..., 0.3866, 0.2060, 0.9570],
         ...,
         [0.8779, 0.5973, 0.2254,  ..., 0.0593, 0.9306, 0.3391],
         [0.2888, 0.6533, 0.0674,  ..., 0.6342, 0.4370, 0.3516],
         [0.5423, 0.1911, 0.4009,  ..., 0.3510, 0.2767, 0.1973]],

        [[0.9845, 0.8683, 0.4665,  ..., 0.4596, 0.8759, 0.4447],
         [0.4441, 0.7407, 0.1578,  ..., 0.3478, 0.4695, 0.8666],
         [0.1465, 0.7695, 0.0055,  ..., 0.4359, 0.9059, 0.5548],
         ...,
         [0.4526, 0.7593, 0.7896,  ..., 0.0055, 0.9452, 0.9610],
         [0.1962, 0.6986, 0.3355,  ..., 0.3636, 0.5133, 0.6083],
         [0.4338, 0.9795, 0.0832,  ..., 0.2932, 0.8089, 0.5553]],

        [[0.1745, 0.0760, 0.9837,  ..., 0.7065, 0.6138, 0.6893],
         [0.2115, 0.4222, 0.5498,  ..., 0.4504, 0.0104, 0.4324],
         [0.6163, 0.3809, 0.1917,  ..., 0.7246, 0.5629, 0.

In [ ]:
### zeros and ones
zero = torch.zeros(3,2)
zero

tensor([[0., 0.],
        [0., 0.],
        [0., 0.]])

In [ ]:
# dtypes
zero.dtype

torch.float32

In [ ]:
#range
range = torch.range(start=2, end=100, step=9)
range

<ipython-input-60-26b3e6163395>:2: UserWarning: torch.range is deprecated and will be removed in a future release because its behavior is inconsistent with Python's range builtin. Instead, use torch.arange, which produces values in [start, end).
  range = torch.range(start=2, end=100, step=9)


tensor([ 2., 11., 20., 29., 38., 47., 56., 65., 74., 83., 92.])

In [ ]:
shape_like= torch.zeros_like(input=range)
shape_like

tensor([0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.])

In [ ]:
# Data types
float_32 = torch.rand([3,9])
float_32.dtype

torch.float32

In [ ]:
float_16 = torch.rand([3,9],
                      dtype=torch.float16,
                      device=None,#'cuda',#None, #cpu, gpu(cuda)
                      requires_grad=False)
float_16.dtype

torch.float16

# Reshaping, stacking, squezzing ans unsqueziing

# Reshaping
Reshapes a tensor to a defined shape

In [ ]:
import torch

x = torch.arange(1., 10.)
x, x.shape

(tensor([1., 2., 3., 4., 5., 6., 7., 8., 9.]), torch.Size([9]))

In [ ]:
# add extra dim
x_reshaped = x.reshape(1,9)
x_reshaped, x_reshaped.shape

(tensor([[1., 2., 3., 4., 5., 6., 7., 8., 9.]]), torch.Size([1, 9]))

In [ ]:
x_reshaped = x.reshape(9,1)
x_reshaped, x_reshaped.shape

(tensor([[1.],
         [2.],
         [3.],
         [4.],
         [5.],
         [6.],
         [7.],
         [8.],
         [9.]]),
 torch.Size([9, 1]))

# Stack
Combine multiple tensors

In [ ]:
x_stacked = torch.stack([x,x,x,x], dim= 0)
x_stacked, x_stacked.ndim, x_stacked.shape

(tensor([[1., 2., 3., 4., 5., 6., 7., 8., 9.],
         [1., 2., 3., 4., 5., 6., 7., 8., 9.],
         [1., 2., 3., 4., 5., 6., 7., 8., 9.],
         [1., 2., 3., 4., 5., 6., 7., 8., 9.]]),
 2,
 torch.Size([4, 9]))

In [ ]:
x_stacked = torch.stack([x,x,x,x], dim= 1)
x_stacked, x_stacked.ndim, x_stacked.shape

(tensor([[1., 1., 1., 1.],
         [2., 2., 2., 2.],
         [3., 3., 3., 3.],
         [4., 4., 4., 4.],
         [5., 5., 5., 5.],
         [6., 6., 6., 6.],
         [7., 7., 7., 7.],
         [8., 8., 8., 8.],
         [9., 9., 9., 9.]]),
 2,
 torch.Size([9, 4]))

# Squeeze
removes all 1 dim

In [ ]:
x_reshaped, x_reshaped.shape, x_reshaped.ndim

(tensor([[1.],
         [2.],
         [3.],
         [4.],
         [5.],
         [6.],
         [7.],
         [8.],
         [9.]]),
 torch.Size([9, 1]),
 2)

In [ ]:
x_squeezed = x_reshaped.squeeze()
x_squeezed, x_squeezed.shape, x_squeezed.ndim

(tensor([1., 2., 3., 4., 5., 6., 7., 8., 9.]), torch.Size([9]), 1)

# Unsqueeze

In [ ]:
x_unsqueezed = x_squeezed.unsqueeze(dim=0)
x_unsqueezed, x_unsqueezed.shape, x_unsqueezed.ndim

(tensor([[1., 2., 3., 4., 5., 6., 7., 8., 9.]]), torch.Size([1, 9]), 2)

In [ ]:
x_unsqueezed = x_squeezed.unsqueeze(dim=1)
x_unsqueezed, x_unsqueezed.shape, x_unsqueezed.ndim

(tensor([[1.],
         [2.],
         [3.],
         [4.],
         [5.],
         [6.],
         [7.],
         [8.],
         [9.]]),
 torch.Size([9, 1]),
 2)

In [79]:
!nvidia-smi

/bin/bash: line 1: nvidia-smi: command not found
